// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'CHANGE_API_KEY',
    appId: '1:789731910065:web:aa513b49f8c9a6aadadd90',
    messagingSenderId: '789731910065',
    projectId: 'auxcom610',
    authDomain: 'auxcom610.firebaseapp.com',
    storageBucket: 'auxcom610.appspot.com',
    measurementId: 'G-S2Y1PBRS2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'CHANGE_API_KEY',
    appId: '1:789731910065:android:dd908b6df73d8dd8dadd90',
    messagingSenderId: '789731910065',
    projectId: 'auxcom610',
    storageBucket: 'auxcom610.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'CHANGE_API_KEY',
    appId: '1:789731910065:ios:6f2ac93cd33179badadd90',
    messagingSenderId: '789731910065',
    projectId: 'auxcom610',
    storageBucket: 'auxcom610.appspot.com',
    iosBundleId: 'com.example.com610',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'CHANGE_API_KEY',
    appId: '1:789731910065:ios:6f2ac93cd33179badadd90',
    messagingSenderId: '789731910065',
    projectId: 'auxcom610',
    storageBucket: 'auxcom610.appspot.com',
    iosBundleId: 'com.example.com610',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'CHANGE_API_KEY',
    appId: '1:789731910065:web:7088a9c59bf1fa62dadd90',
    messagingSenderId: '789731910065',
    projectId: 'auxcom610',
    authDomain: 'auxcom610.firebaseapp.com',
    storageBucket: 'auxcom610.appspot.com',
    measurementId: 'G-4TKV9NV8HE',
  );
}
